CONFIG_I2C=y
CONFIG_I2C_TARGET=y

CONFIG_SHELL=y
CONFIG_I2C_SHELL=y

# CONFIG_DISPLAY=y
# CONFIG_DISPLAY_LOG_LEVEL_DBG=y
#
#
# CONFIG_STM32_LTDC_RGB565=y

# CONFIG_GPIO=y
# CONFIG_GPIO_STM32=y
#
# CONFIG_PINCTRL_LOG_LEVEL_DBG=y
