CONFIG_I2C=y
CONFIG_I2C_TARGET=y

CONFIG_SHELL=y
CONFIG_I2C_SHELL=y

CONFIG_LOG=y
CONFIG_LOG_RUNTIME_DEFAULT_LEVEL=4

CONFIG_MIPI_DSI=y

CONFIG_ADI_ADV7535=y
CONFIG_NT35510=n

CONFIG_DISPLAY=y
CONFIG_DISPLAY_LOG_LEVEL_DBG=y


# CONFIG_STM32_LTDC_RGB565=y
